### ISSUE TITLE
Allow feature to be set in code..

### ISSUE THREAD

**Issue by waynebrantley** [jason-roberts/FeatureToggle#107] opened 2015-10-20 14:16 UTC
Change IFeatureToggle to have a get;set;
This way the value can be read and written to.
The writing my actually change the real setting, or it may just change the value in memory.  So, for the SimpleFeatureToggle, it would read the value from the app settings as normal - only when first created - after that it would cache the value.  That cached value can then be changed by code.   Optionally a SimplePersistanceFeatureToggle may know how to write the value back to where it came from.

**Comment by nlunn** [comment] 2015-10-20 15:33
get;set; on the toggle itself. That could be an idea.
Another idea is to have the toggles read from a file or configuration into the memory. And in the memory you could manipulate the values through the provider?

**Comment by waynebrantley** [comment] 2015-10-21 00:19
yes, that is what I was saying....you could have a get/set that was either persistent or non-persistent (writes the value back or not)

**Comment by jason-roberts** [comment] 2016-01-29 04:50
duplicate of https://github.com/jason-roberts/FeatureToggle/issues/71

**Closed by jason-roberts** 2016-01-29 04:50 UTC
Labels: duplicate
